file=open(input(),'w')
line1=input("line 1 = ")
line2=input("line 2 = ")
line3=input("line 3 = ")
line4=input("line 4 = ")
line5=input("line 5 = ")
line6=input("line 6 = ")
line7=input("line 7 = ")
line8=input("line 8 = ")
line9=input("line 9 = ")
line10=input("line 10 = ")
