list1=[1,2,3,4,5,6,7,8,9,0]
print(list1)
list1.append(6)
print(list1)
print(list1[2])
set1={"srihitha","harsha",1,4,5,"swajith","vamshi","lahari","sanjana"}
print(set1)
print(type(set1))
print(list1)
print(type(list1))
a=1.1j
print(type(a))
b=1
print(type(b))
c=1.1
print(type(c))
d="1.1j"
print(type(d))