print("set opertions example")
set1= {1,2,3,4,5}
set2= {4,5,6,7,8,9,10}
print("intially set1 = ",set1)
print("intially set2 = ",set2)
print("1. Updated operation")
set1.update(set2)
print("after updation set1 = ",set1)
print("2.add operation")
set2.add(11)
print("after adding an element 11 in set2, now set2 = ",set2)
set2.add(4)
print("after adding an element 4 in set2, now set2 = ",set2)
print("3.remove operation")
set2.remove(11)
print("after removing an element 11 in set2, now set2 = ",set2)
print("4.Discard operation")
set2.discard(10)
print("after Discarding an element 10 in set2, now set2 = ",set2)
set2.discard(10)
print("after Discarding an element 10 in set2, now set2 = ",set2)
print("4.pop operation")
set2.pop()
print("set2 after pop operation ,set2= ",set2)
set2.pop()
print("set2 after pop operation ,set2= ",set2)
